// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: lgas.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const saveLga = `-- name: SaveLga :exec
INSERT INTO lgas (name, state_id) VALUES ($1, $2)
`

type SaveLgaParams struct {
	Name    string
	StateID uuid.UUID
}

func (q *Queries) SaveLga(ctx context.Context, arg SaveLgaParams) error {
	_, err := q.db.ExecContext(ctx, saveLga, arg.Name, arg.StateID)
	return err
}
