name: development cd
on:
  push:
    branches: [main]


jobs:
    deploy:
    
        name: Deploying
        permissions:
          id-token: write
          contents: read
        runs-on: ubuntu-latest
        steps:
          - name: Set-Up Go
            uses: actions/setup-go@v4
            with:
              go-version: '1.21.5'
          - name: Checkout Codes
            uses: actions/checkout@v4
          - name : Build The Server Binary
            run: |
             pwd
             scripts/buildprod.sh 
             docker --version
          - name: Build New Docker Image
            run : |
             docker build . -t 042620621262.dkr.ecr.us-east-1.amazonaws.com/naijalocationserver:latest -t 042620621262.dkr.ecr.us-east-1.amazonaws.com/naijalocationserver:${{github.sha}}
             docker image ls 
          - name: Configure aws
            uses: aws-actions/configure-aws-credentials@v4
            with:
              role-to-assume: arn:aws:iam::042620621262:role/githubrole
              aws-region: us-east-1
          - name : Docker Login
            run: docker login -u AWS -p $(aws ecr get-login-password  --region us-east-1) 042620621262.dkr.ecr.us-east-1.amazonaws.com
          - name: Push the docker images to ECR
            run: |
             docker push 042620621262.dkr.ecr.us-east-1.amazonaws.com/naijalocationserver:latest 042620621262.dkr.ecr.us-east-1.amazonaws.com/naijalocationserver:${{github.sha}}