name: development cd
on:
  push:
    branches: [main]

env:
  gpgkey: ${{secrets.GPG_KEY}}


jobs:
  build:
        name: Building and updating docker images.
        permissions:
          id-token: write
          contents: read
        runs-on: ubuntu-latest
        steps:
          - name: Set-Up Go
            uses: actions/setup-go@v4
            with:
              go-version: '1.21.5'
          - name: Checkout Codes
            uses: actions/checkout@v4
          - name : Build The Server Binary 
            run: |
             pwd
             scripts/buildprod.sh 
             docker --version
          - run: |
             mkdir secrets
             gpg --quiet --batch --yes --decrypt --passphrase="$gpgkey" --output secrets/serverpem.pem serverpem.pem.gpg
             chmod 400 "secrets/serverpem.pem"
          - name: SET version to gitenv
            run: echo "deployversion=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          - name: Build New Docker Image
            run : |
             docker build . -t muhammadolammi/naijalocationserver:latest -t muhammadolammi/naijalocationserver:'${{ env.deployversion}}'
             docker image ls 
          - name: Log in To docker 
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          - name: Push Docker images
            run: |
             docker push  muhammadolammi/naijalocationserver --all-tags
  deploy:
      needs: build
      name: Deploying to ec2
      runs-on: ubuntu-latest
      steps:   
        - name: Pull docker image
          run: |
           ssh -o StrictHostKeyChecking=No -tt -i "secrets/serverpem.pem" '${{secrets.EC2_SERVER}}' 'sudo docker pull muhammadolammi/naijalocationserver:latest'
        - name: Stop docker container 
          run: |
            ssh -o StrictHostKeyChecking=No -tt -i "secrets/serverpem.pem" '${{secrets.EC2_SERVER}}' 'sudo docker stop naijalocationserver || true'
            ssh -o StrictHostKeyChecking=No -tt -i "secrets/serverpem.pem" '${{secrets.EC2_SERVER}}' 'sudo docker rm naijalocationserver || true'
        - name: Run New Container
          run: |
             ssh -o StrictHostKeyChecking=No -tt -i "secrets/serverpem.pem" '${{secrets.EC2_SERVER}}' 'sudo docker run --name naijalocationserver -d -p 80:80 -e PORT=80 -e DB_URL="postgresql://postgres:090@Billahlillah@23.22.201.114:5432/naijalocation" muhammadolammi/naijalocationserver:latest'
            