name: cd
on: 
    push:
        # remember to remove dev here 
        branches: [main, dev] 

jobs:
    run_with_git:
        name: Run Server on Git
        runs-on: ubuntu-latest
        environment : ".env"
        steps:
          - name: Set-Up Go
            uses: actions/setup-go@v4
            with:
              go-version: '1.21.5'
          - name: Checkout Codes
            uses: actions/checkout@v4
          - name : Build The Server Binary
            run: |
             pwd
             ls -la
            #  ./secrets/buildprod.sh
             
          - name: Run built Binary
            run: ./bin/naijalocationserver