name: development cd
on:
  push:
    branches: [main]


jobs:
    deploy:
        name: Deploying
        runs-on: ubuntu-latest
        steps:
          - name: Set-Up Go
            uses: actions/setup-go@v4
            with:
              go-version: '1.21.5'
          - name: Checkout Codes
            uses: actions/checkout@v4
          - name : Build The Server Binary
            run: |
             pwd
             scripts/buildprod.sh 
             docker --version
          - name : Configure aws cli
            run : aws configure
            env:
              AWS_ACCESS_KEY_ID : ${{ secrets. AWS_ACESS_ID}}
              AWS_SECRET_ACCESS_KEY : ${{ secrets. AWS_ACCESS_KEY}}
              AWS_DEFAULT_REGION: 'us-east-1'
          - name: Build New Docker Image
            run : |
             scripts/dockerbuild.sh 
             
           