name: development cd
on:
  push:
    branches: [main]

env:
  gpgkey: ${{secrets.GPG_KEY}}


jobs:
    build:
        name: Building and updating docker images.
        permissions:
          id-token: write
          contents: read
        runs-on: ubuntu-latest
        steps:
          - name: Set-Up Go
            uses: actions/setup-go@v4
            with:
              go-version: '1.21.5'
          - name: Checkout Codes
            uses: actions/checkout@v4
          - name : Build The Server Binary 
            run: |
             pwd
             scripts/buildprod.sh 
             docker --version
          - 
            run: |
             mkdir $HOME/secrets
             gpg --quiet --batch --yes --decrypt --passphrase="$gpgkey" --output $HOME/secrets/serverpem.pem serverpem.pem.gpg
             chmod 400 "$HOME/secrets/serverpem.pem"
          - name: Build New Docker Image
            run : |
             docker build . -t 042620621262.dkr.ecr.us-east-1.amazonaws.com/naijalocationserver:latest 
             #-t 042620621262.dkr.ecr.us-east-1.amazonaws.com/naijalocationserver:${{github.sha}}
             docker image ls 
          - name: Configure aws
            uses: aws-actions/configure-aws-credentials@v4
            with:
              role-to-assume: arn:aws:iam::042620621262:role/githubrole
              aws-region: us-east-1
          - name : Docker Login
            run: docker login -u AWS -p $(aws ecr get-login-password  --region us-east-1) 042620621262.dkr.ecr.us-east-1.amazonaws.com
          - name: Push the docker images to ECR
            run: |
             docker push 042620621262.dkr.ecr.us-east-1.amazonaws.com/naijalocationserver:latest
             #docker push 042620621262.dkr.ecr.us-east-1.amazonaws.com/naijalocationserver:${{github.sha}}

    deploy:
      needs: build
      name: Deploying to ec2
      runs-on: ubuntu-latest
      steps: 
        - run: |
           ssh -i "$HOME/secrets/serverpem.pem" ${{secrets.EC2_SERVER}}
