name: development cd
on: 
    push:
        branches: [main] 

jobs:
    run_with_git:
        name: Run Server on Git
        runs-on: ubuntu-latest
        environment : "development"
        steps:
          - name: Set-Up Go
            uses: actions/setup-go@v4
            with:
              go-version: '1.21.5'
          - name: Checkout Codes
            uses: actions/checkout@v4
          - name : Build The Server Binary and set .env values
            run: |
             pwd
             ls -la
             scripts/buildprod.sh 
             docker --version
             ls -la